"""
predictors.py

Public API:
- predict_news_coverage(article_text)
- predict_intent(title, body)
- predict_sensationalism(statement, justification="")
- predict_sentiment(statement)
- predict_article_reputation(article_text=None, sentences=None)
- predict_article_stance(article_text=None, sentences=None)
- analyze_complete_article(article_text)


This is adapted from `combined_pred_model.ipynb` but packaged so teammates can import it.
Sklearn models are loaded from joblib artifacts (generated by train_all.py).
"""
from __future__ import annotations

import os
import re
import json
import uuid
import time
import warnings
from collections import Counter
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# --- sklearn / scipy
from scipy.sparse import hstack, csr_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
import csv

import joblib

# --- NLP
import nltk
from nltk.tokenize import sent_tokenize

# --- sentiment libraries
from nrclex import NRCLex
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# --- transformers (reputation + stance)
import torch
import torch.nn.functional as F
from transformers import (
    DistilBertForSequenceClassification,
    DistilBertTokenizerFast,
    AutoTokenizer,
    AutoModelForSequenceClassification,
)

# ---------------------------
# Paths / artifact names
# ---------------------------
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
ARTIFACT_DIR = os.path.join(_THIS_DIR, "artifacts")

TOPIC_ARTIFACT = os.path.join(ARTIFACT_DIR, "topic_pipeline.joblib")
INTENT_ARTIFACT = os.path.join(ARTIFACT_DIR, "intent_proto.joblib")
SENS_ARTIFACT = os.path.join(ARTIFACT_DIR, "sens_svc.joblib")
SENTIMENT_ARTIFACT = os.path.join(ARTIFACT_DIR, "sentiment_rf.joblib")

# Step up one level from pred_models_training to get the root project directory
ROOT_DIR = os.path.dirname(_THIS_DIR)

DEFAULT_REPUTATION_MODEL_DIR = os.environ.get(
    "REPUTATION_MODEL_DIR", os.path.join(ROOT_DIR, "pred_models_training", "reputation_model")
)
DEFAULT_STANCE_MODEL_DIR = os.environ.get(
    "STANCE_MODEL_DIR", os.path.join(ROOT_DIR, "pred_models_training", "stance_model")
)

# ---------------------------
# Helpers from notebook
# ---------------------------
COLS = [
    "id", "json", "label", "statement", "topic", "speaker", "speaker_job", "state",
    "party", "barely_true", "false", "half_true", "true", "mostly_true",
    "pants_on_fire", "context", "justification"
]

def read_tsv(path: str) -> pd.DataFrame:
    return pd.read_csv(
        path,
        sep="\t",
        header=None,
        names=COLS,
        engine="python",
        quoting=csv.QUOTE_NONE,
        escapechar="\\",
        on_bad_lines="skip",
    )


def _word_count(s: str) -> int:
    return len(re.findall(r"\b\w+\b", s or ""))

def text_of(r: pd.Series) -> str:
    # combine text fields you want the model to learn from
    return " ".join([
        str(r.get("statement", "")),
        str(r.get("context", "")),
        str(r.get("justification", "")),
    ]).strip()

def first_subject(s) -> str:
    # LIAR topic field may contain semicolon/comma separated subjects
    if not isinstance(s, str):
        return "unknown"
    parts = re.split(r"[;,]", s)
    x = parts[0].strip().lower() if parts else ""
    return x if x else "unknown"

def evidence_anchors(text: str) -> Dict[str, int]:
    # simple pattern counts (same spirit as notebook)
    patterns = {
        "quotes": len(re.findall(r"\"", text)),
        "numbers": len(re.findall(r"\b\d+(\.\d+)?\b", text)),
        "links": len(re.findall(r"https?://", text)),
        "proper_nouns": 0,
    }
    try:
        tokens = nltk.word_tokenize(text)
        tags = nltk.pos_tag(tokens)
        patterns["proper_nouns"] = sum(1 for _, t in tags if t == "NNP")
    except Exception:
        patterns["proper_nouns"] = 0
    return patterns

# ---------------------------
# Sentiment feature extraction (NRCLex + VADER)
# ---------------------------
_VADER = SentimentIntensityAnalyzer()

def nrc_doc_score_from_text(text: str) -> Dict[str, float]:
    emo = NRCLex(text or "")
    scores = dict(emo.raw_emotion_scores or {})
    # Normalize by word count to reduce length effects
    wc = max(_word_count(text), 1)
    return {k: v / wc for k, v in scores.items()}

def get_sentiment_class(compound: float) -> str:
    # common VADER thresholds
    if compound >= 0.05:
        return "positive"
    if compound <= -0.05:
        return "negative"
    return "neutral"

def extract_sentiment_features_from_statement(statement: str) -> Dict[str, float]:
    vader = _VADER.polarity_scores(statement or "")
    nrc = nrc_doc_score_from_text(statement or "")
    feats = {
        "vader_neg": vader["neg"],
        "vader_neu": vader["neu"],
        "vader_pos": vader["pos"],
        "vader_compound": vader["compound"],
        "word_count": float(_word_count(statement)),
        "exclamation_count": float((statement or "").count("!")),
        "question_count": float((statement or "").count("?")),
        "uppercase_ratio": float(sum(1 for c in (statement or "") if c.isupper()) / max(len(statement or ""), 1)),
    }
    # Add NRC emotion scores (sparse)
    for k, v in nrc.items():
        feats[f"nrc_{k}"] = float(v)
    return feats

def create_sentiment_feature_dataframe(statements: List[str]) -> pd.DataFrame:
    rows = [extract_sentiment_features_from_statement(s) for s in statements]
    return pd.DataFrame(rows).fillna(0.0)

def _features_for_inference(statements: List[str], scaler: Optional[StandardScaler]=None) -> Tuple[np.ndarray, List[str]]:
    df = create_sentiment_feature_dataframe(statements)
    cols = sorted(df.columns)
    X = df[cols].to_numpy(dtype=np.float32)
    if scaler is not None:
        X = scaler.transform(X)
    return X, cols

# ---------------------------
# Lazy-loaded models
# ---------------------------
_TOPIC_PIPELINE: Optional[Pipeline] = None
_INTENT_PIPELINE: Optional[Pipeline] = None
_SENS_MLP: Optional[Dict] = None
_SENTIMENT_MLP: Optional[Dict] = None

_REP_MODEL = None
_REP_TOK = None

_STANCE_MODEL = None
_STANCE_TOK = None

def _load_joblib(path: str):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing artifact: {path}\n"
            "Run: python -m combined_pred_model.train_all  (from your repo root)\n"
            "to generate artifacts."
        )
    return joblib.load(path)

def _ensure_topic():
    global _TOPIC_PIPELINE
    if _TOPIC_PIPELINE is None:
        _TOPIC_PIPELINE = _load_joblib(TOPIC_ARTIFACT)

def _ensure_intent():
    global _INTENT_PIPELINE
    if _INTENT_PIPELINE is None:
        _INTENT_PIPELINE = _load_joblib(INTENT_ARTIFACT)

def _ensure_sens():
    global _SENS_MLP
    if _SENS_MLP is None:
        _SENS_MLP = _load_joblib(SENS_ARTIFACT)

def _ensure_sentiment():
    global _SENTIMENT_MLP
    if _SENTIMENT_MLP is None:
        _SENTIMENT_MLP = _load_joblib(SENTIMENT_ARTIFACT)

def _ensure_reputation(model_dir: str = DEFAULT_REPUTATION_MODEL_DIR):
    global _REP_MODEL, _REP_TOK
    if _REP_MODEL is None or _REP_TOK is None:
        _REP_MODEL = DistilBertForSequenceClassification.from_pretrained(model_dir)
        _REP_TOK = DistilBertTokenizerFast.from_pretrained(model_dir)
        _REP_MODEL.eval()

def _ensure_stance(model_dir: str = DEFAULT_STANCE_MODEL_DIR):
    global _STANCE_MODEL, _STANCE_TOK
    if _STANCE_MODEL is None or _STANCE_TOK is None:
        _STANCE_TOK = AutoTokenizer.from_pretrained(model_dir)
        _STANCE_MODEL = AutoModelForSequenceClassification.from_pretrained(model_dir)
        _STANCE_MODEL.eval()

# ---------------------------
# Public predict functions
# ---------------------------
def predict_news_coverage(article_text: str) -> Dict:
    """
    Returns {"label": <topic>, "confidence": float, "meta": {...}}
    """
    _ensure_topic()
    proba = None
    label = _TOPIC_PIPELINE.predict([article_text])[0]
    # LinearSVC doesn't expose predict_proba; provide a heuristic confidence
    try:
        scores = _TOPIC_PIPELINE.decision_function([article_text])[0]
        # convert margin to 0-1-ish via softmax
        ex = np.exp(scores - np.max(scores))
        proba = float(np.max(ex / np.sum(ex)))
    except Exception:
        proba = None
    return {"label": label, "confidence": proba, "meta": {"model": "LinearSVC+TFIDF"}}

def predict_intent(title: str = "", body: str = "") -> Dict:
    _ensure_intent()
    
    # _INTENT_PIPELINE is actually a dictionary from train_all.py
    vectorizer = _INTENT_PIPELINE["vectorizer"]
    proto_mat = _INTENT_PIPELINE["proto_mat"]
    class_names = _INTENT_PIPELINE["class_names"]

    text = (title or "").strip() + " " + (body or "").strip()
    
    # Transform text and normalize
    z = vectorizer.transform([text])
    from sklearn.preprocessing import normalize
    zn = normalize(z, norm="l2", axis=1)
    
    # Calculate cosine similarity against the prototypes
    scores = (zn @ proto_mat.T).ravel()
    
    # Find the highest scoring intent
    best_idx = int(np.argmax(scores))
    label = class_names[best_idx]
    conf = float(scores[best_idx])
    
    return {"label": label, "confidence": conf, "meta": {"model": "TFIDF+Prototypes"}}

def predict_sensationalism(statement: str, justification: str = "") -> Dict:
    """
    Predicts sensationalism using the trained SVC pipeline.
    Artifact dict expects: {"tfidf": ..., "model": ..., "evidence_patterns": ...}
    """
    _ensure_sens()
    
    # Load the specific artifacts saved by train_all.py
    tfidf = _SENS_MLP["tfidf"]
    model = _SENS_MLP["model"]
    ev_patterns = _SENS_MLP.get("evidence_patterns", [])

    # Combine text (matches train_all.py: statement + " " + context)
    combined_text = str(statement or "") + " " + str(justification or "")

    # Extract TF-IDF features
    X_tfidf = tfidf.transform([combined_text])

    # Calculate evidence anchor density exactly as train_all.py does
    s = str(statement or "")
    token_re = re.compile(r"[A-Za-z]+")
    ev_re = [re.compile(p, flags=re.I) for p in ev_patterns]

    hits = sum(len(r.findall(s)) for r in ev_re)
    toks = max(1, len(token_re.findall(s)))
    dens = np.log1p(hits) / max(10, toks)
    ev_score = float(np.clip(dens, 0.0, 0.2))

    X_ev = np.array([[ev_score]])

    # Combine features using hstack (Scipy Sparse Matrix)
    X = hstack([X_tfidf, X_ev])

    # Predict (model outputs 1 for sensational, 0 for neutral based on your THRESHOLD)
    pred_val = model.predict(X)[0]
    label = "sensational" if pred_val == 1 else "neutral"

    # Get Confidence Score
    conf = None
    if hasattr(model, "predict_proba"):
        conf = float(np.max(model.predict_proba(X)[0]))

    return {
        "label": label, 
        "confidence": conf, 
        "meta": {"model": "SVC+TFIDF+Anchors"}
    }

def predict_sentiment(statement: str) -> Dict:
    """
    Artifact is dict: {"scaler": ..., "clf": ..., "cols": [...]}
    """
    _ensure_sentiment()
    scaler = _SENTIMENT_MLP["scaler"]
    clf = _SENTIMENT_MLP["clf"]
    cols = _SENTIMENT_MLP["cols"]
    feats = extract_sentiment_features_from_statement(statement or "")
    df = pd.DataFrame([feats]).fillna(0.0)
    for c in cols:
        if c not in df.columns:
            df[c] = 0.0
    X = df[cols].to_numpy(dtype=np.float32)
    X = scaler.transform(X)
    label = clf.predict(X)[0]
    conf = None
    if hasattr(clf, "predict_proba"):
        conf = float(np.max(clf.predict_proba(X)[0]))
    return {"label": label, "confidence": conf, "meta": {"model": "MLP+VADER+NRC"}}

def _hf_predict_sentence_labels(
    sentences: List[str],
    tokenizer,
    model,
) -> Tuple[List[int], List[float]]:
    # returns labels + confidences per sentence
    labels = []
    confs = []
    with torch.no_grad():
        for s in sentences:
            enc = tokenizer(
                s,
                truncation=True,
                padding=True,
                max_length=256,
                return_tensors="pt",
            )
            out = model(**enc)
            logits = out.logits
            probs = torch.softmax(logits, dim=-1).cpu().numpy()[0]
            lab = int(np.argmax(probs))
            labels.append(lab)
            confs.append(float(np.max(probs)))
    return labels, confs

def predict_article_reputation(article_text: Optional[str] = None, sentences: Optional[List[str]] = None) -> Dict:
    """
    Sentence-level majority vote. Returns:
    {
      "label": "low|medium|high" (depends on your fine-tuned label order),
      "confidence": 0-1,
      "sentence_votes": Counter,
      "sentences": [{"text":..., "label_id":..., "confidence":...}, ...]
    }
    """
    _ensure_reputation()
    if sentences is None:
        if article_text is None:
            raise ValueError("Provide article_text or sentences.")
        sentences = sent_tokenize(article_text)
    label_ids, confs = _hf_predict_sentence_labels(sentences, _REP_TOK, _REP_MODEL)
    votes = Counter(label_ids)
    top_id, top_ct = votes.most_common(1)[0] if votes else (0, 0)
    avg_conf = float(np.mean([c for i, c in zip(label_ids, confs) if i == top_id])) if votes else None

    # NOTE: update mapping to match your fine-tuned model config id2label if needed
    id2label = getattr(_REP_MODEL.config, "id2label", None) or {0: "low", 1: "medium", 2: "high"}
    label = id2label.get(top_id, str(top_id))

    return {
        "label": label,
        "confidence": avg_conf,
        "sentence_votes": dict(votes),
        "sentences": [{"text": s, "label_id": i, "confidence": c} for s, i, c in zip(sentences, label_ids, confs)],
        "meta": {"model": "DistilBERT sentence vote"},
    }

def predict_article_stance(article_text: Optional[str] = None, sentences: Optional[List[str]] = None) -> Dict:
    _ensure_stance()
    if sentences is None:
        if article_text is None:
            raise ValueError("Provide article_text or sentences.")
        sentences = sent_tokenize(article_text)
    label_ids, confs = _hf_predict_sentence_labels(sentences, _STANCE_TOK, _STANCE_MODEL)
    votes = Counter(label_ids)
    top_id, top_ct = votes.most_common(1)[0] if votes else (0, 0)
    avg_conf = float(np.mean([c for i, c in zip(label_ids, confs) if i == top_id])) if votes else None

    id2label = getattr(_STANCE_MODEL.config, "id2label", None) or {0: "against", 1: "neutral", 2: "favor"}
    label = id2label.get(top_id, str(top_id))

    return {
        "label": label,
        "confidence": avg_conf,
        "sentence_votes": dict(votes),
        "sentences": [{"text": s, "label_id": i, "confidence": c} for s, i, c in zip(sentences, label_ids, confs)],
        "meta": {"model": "AutoModel sentence vote"},
    }

def analyze_complete_article(article_title: str = "", article_text: str = "") -> dict:
    """
    Complete article analysis using sentence-level voting from all 6 models.
    """
    results = {
        "predictions": {}
    }

    try:
        sentences = nltk.sent_tokenize(article_text or "")
    except Exception:
        sentences = []

    # Basic cleanup
    sentences = [s.strip() for s in sentences if s.strip()]

    # If NLTK didn't find sentences, fall back to treating the whole text as one "sentence"
    if not sentences and article_text.strip():
        sentences = [article_text.strip()]

    # If still nothing, bail
    if not sentences:
        return {"error": "No valid sentences found to analyze."}

    # Optional length filter (less strict than before)
    sentences = [s for s in sentences if len(s) > 5]
    if not sentences:
        sentences = [article_text.strip()]

    # Initialize counters for voting
    news_coverage_votes = []
    intent_votes = []
    sensationalism_votes = []
    sentiment_votes = []

    # --- Per-sentence models ---
    for sentence in sentences:
        # 1. News Coverage Prediction
        try:
            news_coverage = predict_news_coverage(sentence)["topic"]
            news_coverage_votes.append(news_coverage)
        except Exception:
            pass

        # 2. Intent Prediction
        try:
            intent_result = predict_intent(title="", body=sentence)
            intent_votes.append(intent_result["primary_intent"])
        except Exception:
            pass

        # 3. Sensationalism Prediction
        try:
            sensationalism_result = predict_sensationalism(sentence)
            sensationalism_votes.append(sensationalism_result["label"])
        except Exception:
            pass

        # 4. Sentiment Prediction
        try:
            sentiment = predict_sentiment(sentence)["sentiment"]
            sentiment_votes.append(sentiment)
        except Exception:
            pass

    # 5. Reputation Prediction (uses pre-split sentences)
    try:
        reputation_result = predict_article_reputation(sentences=sentences)
        results["predictions"]["reputation"] = {
            "level": reputation_result["final_label"],
            "model": "DistilBERT (Sentence-level Majority Vote)",
        }
    except Exception as e:
        results["predictions"]["reputation"] = {"error": str(e)}

    # 6. Stance Prediction (uses pre-split sentences)
    try:
        stance_result = predict_article_stance(sentences=sentences)
        results["predictions"]["stance"] = {
            "stance": stance_result["final_label"],
            "model": "AutoModel (Sentence-level Majority Vote)",
        }
    except Exception as e:
        results["predictions"]["stance"] = {"error": str(e)}

    # --- Vote Aggregation for looping models ---

    # News Coverage
    try:
        if news_coverage_votes:
            article_news_coverage = Counter(news_coverage_votes).most_common(1)[0][0]
            results["predictions"]["news_coverage"] = {"topic": article_news_coverage}
        else:
            results["predictions"]["news_coverage"] = {"error": "No votes cast"}
    except Exception:
        results["predictions"]["news_coverage"] = {"error": "Processing error"}

    # Intent
    try:
        if intent_votes:
            article_intent = Counter(intent_votes).most_common(1)[0][0]
            results["predictions"]["intent"] = {"primary_intent": article_intent}
        else:
            results["predictions"]["intent"] = {"error": "No votes cast"}
    except Exception:
        results["predictions"]["intent"] = {"error": "Processing error"}

    # Sensationalism
    try:
        if sensationalism_votes:
            article_sensationalism = Counter(sensationalism_votes).most_common(1)[0][0]
            results["predictions"]["sensationalism"] = {"label": article_sensationalism}
        else:
            results["predictions"]["sensationalism"] = {"error": "No votes cast"}
    except Exception:
        results["predictions"]["sensationalism"] = {"error": "Processing error"}

    # Sentiment
    try:
        if sentiment_votes:
            article_sentiment = Counter(sentiment_votes).most_common(1)[0][0]
            results["predictions"]["sentiment"] = {"sentiment": article_sentiment}
        else:
            results["predictions"]["sentiment"] = {"error": "No votes cast"}
    except Exception:
        results["predictions"]["sentiment"] = {"error": "Processing error"}

    # Return only the predictions dict
    return results["predictions"]